export default {
  INIT_DIALOG: 'INIT_DIALOG',
  REMOVE_DIALOG: 'REMOVE_DIALOG',
  UPDATE_DIALOG: 'UPDATE_DIALOG',
  TOGGLE_HIDDEN_DIALOGS_LIST: 'TOGGLE_HIDDEN_DIALOGS_LIST',
  SET_MAX_AVAILABLE_OPENED_DIALOGS: 'SET_MAX_AVAILABLE_OPENED_DIALOGS',
  RESET_UNREAD_MESSAGES_COUNT: 'RESET_UNREAD_MESSAGES_COUNT',
  UPDATE_NEW_DIALOG_NOTIFICATIONS: 'UPDATE_NEW_DIALOG_NOTIFICATIONS',
  ADD_TEXTS_TO_DIALOG: 'ADD_TEXTS_TO_DIALOG',
  UPDATE_TEXT_IN_DIALOG: 'UPDATE_TEXT_IN_DIALOG',
};